trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'tomsilhouette/my-react-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
- stage: Push
  displayName: Push DevOps base image
  jobs:
  - job: Push
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'my-react-app'
        targetPath: '$(Pipeline.Workspace)'
    - task: Bash@3
      displayName: Load Docker Image
      inputs:
        targetType: 'inline'
        script: |      
          docker load --input $(Pipeline.Workspace)/MY_IMAGE_FILE.tar
          docker tag tomsilhouette/my-react-app:$(tag) tomsilhouette/my-react-app:MY_ADDITIONAL_TAG
    - task: Docker@2
      displayName: push development tags
      inputs:
        containerRegistry: 'docker'
        repository: 'tomsilhouette/my-react-app'
        command: 'push'
        tags: | 
          $(tag)
    - task: Docker@2
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      displayName: push 0-devops tag
      inputs:
        containerRegistry: 'docker'
        repository: 'tomsilhouette/my-react-app'
        command: 'push'
        tags: | 
          MY_ADDITIONAL_TAG
